# Generated by Django 3.2 on 2022-12-07 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='clothes_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='main.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='clothes_image',
            field=models.ImageField(blank=True, null=True, upload_to='clothes', verbose_name='Картинка'),
        ),
    ]
