# Generated by Django 3.2 on 2022-12-12 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_clothescolor_clothesinstock_clothessize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothesinstock',
            name='clothes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_in_stock', to='main.clothes'),
        ),
        migrations.AlterField(
            model_name='clothesinstock',
            name='clothes_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_in_stock', to='main.clothescolor'),
        ),
        migrations.AlterField(
            model_name='clothesinstock',
            name='clothes_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_in_stock', to='main.clothessize'),
        ),
    ]
